[package]
name = "remember-me"
version = "1.0.0"
edition = "2021"

[workspace]

[lib]
name = "remember_me"
path = "src/lib_test.rs"

[dependencies]
jsonwebtoken = "8.3"
chrono = { version = "0.4", features = ["serde"] }
