[package]
name = "shipping-calculator"
version = "1.0.0"
edition = "2021"

[workspace]

[lib]
name = "shipping_calculator"
path = "src/lib_test.rs"

[dependencies]
uuid = { version = "1.6", features = ["v4"] }
rust_decimal = "1.33"
