[package]
name = "shopping-cart"
version = "1.0.0"
edition = "2021"

[workspace]

[lib]
name = "shopping_cart"
path = "src/lib_test.rs"

[dependencies]
uuid = { version = "1.6", features = ["v4"] }
rust_decimal = "1.33"
