[package]
name = "multi-factor-auth"
version = "1.0.0"
edition = "2021"

[workspace]

[lib]
name = "multi_factor_auth"
path = "src/lib_test.rs"

[dependencies]
jsonwebtoken = "8.3"
chrono = { version = "0.4", features = ["serde"] }
