[package]
name = "device-tracking"
version = "1.0.0"
edition = "2021"

[workspace]

[lib]
name = "device_tracking"
path = "src/lib_test.rs"

[dependencies]
jsonwebtoken = "8.3"
chrono = { version = "0.4", features = ["serde"] }
