[package]
name = "rustform_studio"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
anyhow = "1.0"
axum = { version = "0.7", features = ["macros"] }
chrono = { version = "0.4", features = ["serde"] }
dotenvy = "0.15"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sqlx = { version = "0.7", features = ["runtime-tokio-rustls", "sqlite", "chrono", "uuid", "migrate"] }
tokio = { version = "1.0", features = ["full"] }
tower = { version = "0.4", features = ["full"] }
tower-http = { version = "0.4", features = ["trace", "cors"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
uuid = { version = "1.6", features = ["v4", "serde"] }

# Studio-specific dependencies
serde_yaml = "0.9"
regex = "1.10"
semver = "1.0"
url = "2.4"
zip = "0.6"
futures = "0.3"
walkdir = "2.3"
toml = "0.8"
reqwest = { version = "0.11", features = ["json"] }
base64 = "0.21"
urlencoding = "2.1"

# Local dependencies
rustform-core = { path = "../../rustform-core" }
rustform-codegen = { path = "../../rustform-codegen" }
