project_name: test-init-project
version: "0.1.0"

database:
  type: sqlite
  url_env: DATABASE_URL

api:
  models:
    Example:
      table_name: examples
      fields:
        id:
          type: integer
          primary_key: true
          auto_increment: true
        name:
          type: string
          required: true
        description:
          type: string
        created_at:
          type: datetime
          auto_now_add: true

  endpoints:
    - path: /examples
      model: Example
      crud:
        create: true
        read_all: true
        read_one: true
        update: true
        delete: true

middleware:
  - logger: true
  - cors:
      allow_origin: "*"
